### PR TITLE
Log successes similar to failures

### PR DESCRIPTION
**Pull request by hasnat**
Might not be what this repo had planned but trying to keep logging behaviour of failure and success messages consistent

### CODE REVIEW

**Comment by torokmark** [comment]
The idea is good, though the whole approach of assert.sh comes from the assertion mechanism of jUnit.

I would leave the PR open for a discussion.

**Comment by hasnat** [comment]
cool, am more used to verbose unit tests. Or should there be a parameter/env_var to enable such verbosity?

**Comment by finwo** [comment]
Based on experience with other unit-testing frameworks (phpunit, jest, istanbul & more):

Single asserts in tests usually only notify when something bad happened AND a message is supplied.
The test itself prints only 1 line of success (or fail, if that's the case).

These 2 common assumptions are fulfilled within this library so I don't see the need to supply messages on an assert success.

One possible solution would be to add different logging levels & maybe even a different message for success vs. failure. This way the default behavior wouldn't change but this project is still able to provide @hasnat's expectations.

---

**Update:** Logging both outcomes is already available in some form:

```sh
assert_eq "Hello" "World" && log_success "Matches =D" || log_failure "Doesn't match :("
```

**Comment by torokmark** [comment]
I am closing this request due to the following reasons.
* As I mentioned assert.sh follows the junit approach, 
* and @finwo provided a neat way how to use the lib with successes similar to failures

**Pull request closed without merging**
